version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/"
    target-branch: "dev"
    schedule:
      interval: "daily"
    groups:
      open-source-license:
        patterns:
          - "*"